apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: docker-private-registry-ingress
    namespace: infrastructure
spec:
    backend:
        serviceName: docker-private-registry
        servicePort: 5000
