apiVersion: v1
kind: Namespace
metadata:
  name: example

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: example
  labels:
    project: example
    module: app
spec:
  selector:
    matchLabels:
      project: example
      module: app
  template:
    metadata:
      labels:
        project: example
        module: app
    spec:
      containers:
        - name: example-app
          image: localhost:5000/example-app
          ports:
            - name: webserver-port
              containerPort: 8080
              hostPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              memory: 350Mi

---

apiVersion: v1
kind: Service
metadata:
  name: example-app
  namespace: example
spec:
  selector:
    project: example
    module: app
  ports:
    - name: webserver-port
      port: 8080
      protocol: TCP

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-app-ingress
  namespace: example
spec:
  rules:
    - host: example.127.0.0.1.xip.io
      http:
        paths:
          - backend:
              serviceName: example-app
              servicePort: 8080
